@aws_api_gateway_endpoint = yx36mlps95
@auth = dgf834-20260331
@host_aws = https://{{aws_api_gateway_endpoint}}.execute-api.us-east-1.amazonaws.com/Prod
@host_local = http://127.0.0.1:3000
@host={{host_aws}}


### Generate Addresses
POST {{host}}/gen HTTP/1.1
content-type: application/json
User-Agent: rest-client
auth: {{auth}}

{
    "address_in": "French",
    "format": "JSON",
    "language": "in French"
}

### Cleanse Addresses
POST {{host}}/cleanse/gpt HTTP/1.1
content-type: application/json
User-Agent: rest-client
Accept-Encoding: *
auth: {{auth}}

{
    "params": {
        "translate_output": "true"
    },
    "addresses": 
    # {
    #     "1":"123 Main St, ON, Toronto, Canada, M5V 2B7",
    #     "2":"V6G 1C4 789 Elm St, Apt 456, Vancouver, BC",
    #     "3":"To Steve Montreal QC 567 Apple St Canada H3B 1C8",
    #     "4":"987 Maple St Calgary AB",
    #     "5":"Oak 654 Ottawa Ontario K1N 5W5 Canada"
    # }
    # {
    #     "1": "北京市朝阳区建国门外大街10号院",
    #     "2": "四川省成都市武侯区天府大道中段",
    #     "3": "广东省深圳市福田区华强北路",
    #     "4": "江苏省南京市鼓楼区中山东路",
    #     "5": "山东省青岛市市南区香港中路"
    # }
    {
        "1": "Marie Dubois",
        "2": "12 Rue de la Paix",
        "3": "Paris, France 75002",
        "5": "Étienne Leroux",
        "6": "25 Avenue du Général de Gaulle",
        "7": "Lyon, France 69007",
        "9": "Sophie Moreau",
        "10": "8 Place Bellecour",
        "11": "Marseille, France 13001",
        "13": "Antoine Lefevre",
        "14": "16 Boulevard Haussmann",
        "15": "Nice, France 06000",
        "17": "Camille Martin",
        "18": "10 Rue des Fleurs",
        "19": "Toulouse, France 31000"
    }
}